config/routes.rb
Rails.application.routes.draw do
  root to:'tasks#index'
  resources :tasks
  
  #ユーザー登録
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :new ,:create]
  
  #ログイン機能
  get 'login', to: 'sessions#new'
  post'login', to: 'sessions#create'
  delete'logout', to:'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, presence: true, length: { maximum: 10}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create #ログイン処理を担当
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success]='ログインに成功しました'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:update,:destroy,:show,:edit]
  def index
    @task = current_user.tasks.build
    @tasks = current_user.tasks.order('created_at DESC').page(params[:page])#一覧表示用

  end

  def show    
    set_task
  end
  
  def new
    @task = Task.new
  end
  

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save #成功でtrue、失敗でfalse
      flash[:success] = 'タスクが正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger]='タスクが投稿されませんでした'
      render :new
    end
  end
  
  def edit
    set_task
  end
  
  def update
    set_task
    if @task.update(task_params)
      flash[:success]="タスクは正常の更新されました"
      redirect_to @task
    else
      flash.now[:danger]="タスクは更新されませんでした"
      render :edit
    end
  end
  
  def destroy
    set_task
    @task.destroy
    
    flash[:success] = "Messageは正常に削除されました"
    redirect_to tasks_url
  end

  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  #StrongParameter
  def task_params
    params.require(:task).permit(:content,:status,:user)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      flash[:danger] = '権限がありません'
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]='ユーザーを登録しました'
      redirect_to root_path #ユーザー登録成功時のジャンプ先は要検討
    else
      flash.now[:danger]='ユーザーの登録に失敗しました'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message|%>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %><!--ログイン中-->
            <li><%= link_to  '新規タスクの投稿', new_task_path %></li>
            <li class= "dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My Task', root_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %><!--ログインしてない時-->
            <li><%= link_to  'ユーザー登録', signup_path %></li>
            <li><%= link_to  'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class ="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div id="error_explanation">
        <ul>
          <% task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        </div>
      <% end %>
  
    <div class="form-group">
      <%= f.label :content,'タスク' %>
      <%= f.text_field :content,class: "form-control" %>
    </div>
  
    <div class = "form-group">
      <%= f.label :status,'ステータス' %>
      <%= f.text_field :status,class: "form-control" %>
    </div>
  
    <%= f.submit '投稿',class:'btn btn-primary'%>

    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id:<%= @task.id %>の編集ページ</h1>

<%= render'form',task: @task %>

app/views/tasks/index.html.erb
  <h1><%= current_user.name %>のタスク一覧</h1>
  <ul>
    <% @tasks.each do |task|%>
    <li>
      <%= link_to task.id,task%>：<%= task.content %> &gt; <%= task.status %>
    </li>
    <% end %>
  </ul>
  <%= paginate @tasks %>

  <%= link_to "新規タスクの投稿",new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render'form',task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> の詳細ページ</h1>
<p>タスク：<%=@task.content %> </p>
<p>ステータス：<%=@task.status %> </p>

<%= link_to "タスク一覧に戻る" , tasks_path %>
<%= link_to "編集" , edit_task_path %>
<%= link_to "削除" , @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>